name: Build & Publish Docker Image to GitHub Container Registry

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: production

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    # Set environment variables
    - run: echo RELEASE=$(cat ./src/package.json | jq -r .release) >> $GITHUB_ENV
    
    # Build & Publish
    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: ghcr.io/${{ github.repository }}:nightly, ghcr.io/${{ github.repository }}:${{ env.RELEASE }}-nightly
